default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["DEV_DATABASE"] || 'pulitzer_development' %>
  username: <%= ENV["DEV_DATABASE_USERNAME"] || '' %>
  password: <%= ENV["DEV_DATABASE_PASSWORD"] || '' %>
  host: <%= ENV["DEV_DATABASE_HOST"] || '127.0.0.1' %>
  port: <%= ENV["DEV_DATABASE_PORT"] || '5435' %>


production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 14 %>
